config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'

  root 'dashboard#index'
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :weather, only: [:index]
  resources :books do
    collection do
      get 'search'
    end
  end
  # resources :books, only: [:index]
  resources :customers, only: [:index, :statistic] do
    collection do
      get 'statistic'
    end
  end
  resources :tasks, except: [:edit] do
    member do
      post 'mark_done'
    end
  end

  if Rails.env.development?
    Rails.application.routes.draw do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks

	validates :title, presence: true
	validates :author, presence: true
	validates :published_year, presence: true
	validates :excerpt, presence: true

	def as_indexed_json(_options = {})
		as_json(only: %w[title author published_year])
	end

	def self.search(query)
		__elasticsearch__.search(
			{
				query: {
					multi_match: {
						query: query,
						fields: %w[title^10 author^5 excerpt]
					}
				}
			}
		)
	end

	settings index: { number_of_shards: 1 } do
		mappings dynamic: 'false' do
			indexes :title, analyzer: 'english', index_options: 'offsets'
			indexes :author, analyzer: 'english', index_options: 'offsets'
			indexes :published_year, type: 'integer'
			indexes :excerpt, analyzer: 'english', index_options: 'offsets'
		end
	end
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :status, inclusion: { in: %w[TO DO DONE OVERDUE] }
  validates :due_date, presence: true
end

app/models/weather.rb
# frozen_string_literal: true

class Weather < ApplicationRecord
  validates :current_date, presence: true
  validates :current_temperature,
            numericality: { greater_than_or_equal_to: -100, less_than_or_equal_to: 100, precision: 1 }
  validates :temperature_last_year,
            numericality: { greater_than_or_equal_to: -100, less_than_or_equal_to: 100, precision: 1 }
  validates :temperature_difference,
            numericality: { greater_than_or_equal_to: -100, less_than_or_equal_to: 100, precision: 1 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		if params[:query].present?
			@books = Book.search(params[:query]).paginate(page: params[:page], per_page: 20)
		else
			@books = Book.all.paginate(page: params[:page], per_page: 20)
		end
	end

	def search
		redirect_to books_path(query: params[:search][:query])
	end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :load_cached_customers, only: [:index, :statistic]

  def index
    @customers = customers.paginate(page: params[:page], per_page: 20)
  end

  def statistic
    @statistic = Customers::CustomerStatistic.new(customers).perform
  end

  private

  def customers
    @cached_customers ||= load_cached_customers
  end

  def load_cached_customers
    Customers::CacheCustomers.new.fetch_cached_customers
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index; end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  def index
    @tasks = Task.all.order(due_date: :asc).paginate(page: params[:page], per_page: 5)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    task_service = ::Task::CreateTask.new(@task)

    if task_service.create_task
      redirect_to tasks_path, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def destroy
    if set_task.destroy
      redirect_to tasks_path, notice: 'Task was successfully deleted.'
    else
      redirect_to tasks_path, alert: 'Error deleting task.'
    end
  end

  def mark_done
    ::Task::ChangeTaskStatus.new(set_task).call
    redirect_to tasks_path, notice: 'Task status successfully changed.'
  rescue StandardError => e
    redirect_to tasks_path, alert: "Error marking task as done: #{e.message}"
  end

  private

  def set_task
    @set_task ||= Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :due_date)
  end
end

app/controllers/weather_controller.rb
# frozen_string_literal: true

class WeatherController < ApplicationController
  def index
    @weathers = Weather.all.paginate(page: params[:page], per_page: 15)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/books/index.slim
.container.alert.alert-warning
  p HINT:
  p Here is realized a elastic search of some phrases in book`s data
  P Write what you want to search and push ENTER (Author, Title or description)
.container
  .btn-toolbar.justify-content-md-center
    .row.mt-3
      .col
        = simple_form_for :search, url: search_books_path, method: :get do |f|
          = f.input :query, label: false, input_html: { class: 'form-control', placeholder: 'Search books...' }
          = f.button :submit, class: 'button-old-primary', style: 'display: none'
h1.mt-2 All books
table.table.table-bordered
  thead
    tr
      th Title
      th Author
      th Year
  tbody
    - @books&.each do |book|
      tr
        td= book.title
        td= book.author
        td= book.published_year
.pagination-centered
  = will_paginate @books, renderer: BootstrapPagination::Rails

app/views/customers/index.slim
.container.alert.alert-warning
  p HINT: We have 100 customers seeded in DB by faker
  p Here we can see customer's statistic with cashing by Redis for avoiding big quontity of DB queries.
= link_to 'Customer statistics (analysis of hashed data)',
 statistic_customers_path,
 class: "button-old-primary"
h1.mt-4 All customers
table.table.table-bordered
  thead
    tr
      th Name
      th Age
      th Email
      th Country
      th Balance
  tbody
    - @customers.each do |customer|
      tr
        td= customer.full_name
        td= customer.age
        td= customer.email
        td= customer.country
        td= customer.balance
.pagination-centered
  = will_paginate @customers, renderer: BootstrapPagination::Rails

app/views/customers/statistic.slim
h1 Customer`s statistic
h4.mt-5 Length of customer`s names
table.table.table-bordered
  thead
    tr
      th Name
      th Length
  tbody
    - @statistic[:longest_names].each do |name, length|
      tr
        td= name
        td= length

h4.mt-5 The most popular customer`s countries
table.table.table-bordered
  thead
    tr
      th Country
      th Count
  tbody
    - @statistic[:popular_countries].each do |country, count|
      tr
        td= country
        td= count

h4.mt-5 The richest customers
table.table.table-bordered
  thead
    tr
      th Name
      th Balance
  tbody
    - @statistic[:richest_customers].each do |customer|
      tr
        td= customer.keys.join
        td= customer.values.join

app/views/dashboard/index.slim
.d-flex.justify-content-center.py-3
  .container
    h4 This project is for learning Sidekiq, Redis and CRON.
    .row
      p 1) learn scheduled tasks with CRON and Sidekiq
      p 2) learn about cashing with Redis
      p 3) create own CSS styles
    .row
      h4 I used:
    .row
      p 1) Database: PostgreSQL
      p 2) SLIM templates against ERB
      p 3) Gem 'SimpleForm' for my forms
      p 4) Redis + Sidekiq + CRON for background jobs
      p 5) Bootstrap and own CSS for styles
      p 6) gem "will_paginate" for pagination
      p 7) gem "faker" for seeding DB
      p 8) Redis for cashing data
      p 9) used gem "rubocop" as a linter
    .row
      h4 Some files that are normally ignored in GIT will not be ignored for the sake of clarity.

app/views/layouts/application.slim
doctype html
html
  head
    title SidekiqTasks
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    = render "shared/navbar"
    .container.my-5
      = render "shared/flashes"
      = yield

app/views/shared/_flashes.slim
- if notice
  .alert.alert-info
    = notice
- if alert
  .alert.alert-warning
    = alert

app/views/shared/_navbar.slim
.navbar.navbar-expand-sm.navbar-light.navbar-drop
  .container-fluid
    ul.navbar-nav.me-auto
      li.nav-item
        = link_to "APP info", root_path, class: "nav-link"
      li.nav-item
        = link_to "Sidekiq jobs", tasks_path, class: "nav-link"
      li.nav-item
        = link_to "Scheduled jobs", weather_index_path, class: "nav-link"
      li.nav-item
        = link_to "Redis cashing", customers_path, class: "nav-link"
      li.nav-item
        = link_to "Keyword search", books_path, class: "nav-link"
      li.nav-item
        = link_to "Other search", "#", class: "nav-link"

app/views/tasks/index.slim
.container.alert.alert-warning
  p HINT: We are setting alert time and Sidekiq will send a mail 10 minutes before this.
  p All tasks will be closed automatic in 24h after alert time.
= link_to 'Create new task', new_task_path, class: "button-old-primary"
h1.mt-4 All tasks
- @tasks.each do |task|
  .mt-4
    .container.border.border-dark.rounded-3
      .d-flex.justify-content-between.align-items-center
        h3.mt-2 = task.name
        - if task.status == "TO DO"
          span.badge.bg-primary = task.status
        - else
          span.badge.bg-success = task.status
      h5 = task.description
      p Alert time: #{task.due_date.strftime("%d.%m.%Y %H:%M")}
      .container.d-flex.justify-content-between.mb-2
        .row
          .col
            = link_to 'Edit', "#", class: "button-old-primary ml-2 mb-4"
          .col
            - if task.status == "TO DO"
              = link_to 'Close', mark_done_task_path(task), class: "button-old-primary button-success"
            - else
              = button_to "Open", mark_done_task_path(task), method: :post, class: "button-old-primary button-success"
          .col
            = button_to "Delete", task_path(task), method: :delete, class: "button-old-primary button-danger"
.pagination-centered
  = will_paginate @collection, renderer: BootstrapPagination::Rails

app/views/tasks/new.slim
= simple_form_for @task, data: { turbo_frame: 'new_task' } do |f|
  = f.input :name
  = f.input :description
  = f.datetime_field :due_date
  .container.row
    = f.button :submit, class: "btn btn-success mt-2"
= link_to "See all tasks", tasks_path, class: "btn btn-primary mt-2"

app/views/tasks/show.slim
p show action

app/views/weather/index.slim
.container.alert.alert-warning
  p HINT: We fetch weather in Lviv, Ukraine every day and store it in database.
  p We use REST API and Sidekiq + CRON for requests.
table.table.table-bordered
  thead
    tr
      th Date
      th Current Temperature
      th Temperature Last Year
      th Temperature Difference
  tbody
    - @weathers.each do |weather|
      tr
        td= weather.current_date
        td= weather.current_temperature
        td= weather.temperature_last_year
        td= weather.temperature_difference
.pagination-centered
  = will_paginate @weathers, renderer: BootstrapPagination::Rails